### ISSUE TITLE
Notworking with WorldEdit for 1.13 string-id build

### ISSUE THREAD

**Issue by Ghost-chu** [Zrips/Residence#173]
22:55:05 INFO]: [Residence] Enabling Residence v4.8.0.0
[22:55:05 INFO]: [w2] red_hat >> ？
[22:55:05 INFO]: [Residence] Can't find world with (HerobrineWorld) name
[22:55:05 INFO]: [Residence] Can't find world with (w2_flat) name
[22:55:05 INFO]: [Residence] Can't find world with (answer) name
[22:55:05 INFO]: [Residence] Can't find world with (nn) name
[22:55:05 INFO]: [Residence] Can't find world with (action) name
[22:55:05 INFO]: [Residence] Can't find world with (test) name
[22:55:05 INFO]: Can't find effect for Selected Frame with this name, it was set to default
[22:55:05 INFO]: Can't find effect for Selected Frame with this name, it was set to default
[22:55:05 INFO]: [Residence] Found Vault using permissions plugin:PermissionsEx
[22:55:05 INFO]: [Residence] Scanning for economy systems...
[22:55:05 INFO]: [Residence] Found Vault using economy system: CMIEconomy
[22:55:06 WARN]: [Residence] Save directory does not exist...
[22:55:06 WARN]: [Residence] Please restart server
[22:55:06 INFO]: [Residence] Starting auto CleanUp (98/0)!
[22:55:06 INFO]: [Residence] Auto CleanUp deleted 0 residences!
[22:55:06 ERROR]: Error occurred while enabling Residence v4.8.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/selections/Selection
at com.bekvon.bukkit.residence.Residence.setWorldEdit(Residence.java:875) ~[?:?]
at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:715) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1750) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1554) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_162]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:986) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.selections.Selection
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_162]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-48]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_162]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
... 26 more
[22:55:06 INFO]: [Residence] Disabling Residence v4.8.0.0

I download WorldEdit from there http://builds.enginehub.org/job/worldedit?branch=string-ids

**Comment by Ghost-chu** [comment]
I can uninstall WE,My Worldguard and other plugin need WE
